export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS';
export const ALL_ROOMS_FAILED = 'ALL_ROOMS_FAILED';
export const ROOMS_DETAILS_SUCCESS = 'ROOMS_DETAILS_SUCCESS';
export const ROOMS_DETAILS_FAILED = 'ROOMS_DETAILS_FAILED';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
